### ISSUE TITLE
error: package directory 'EV_sim/examples' does not exist

### ISSUE THREAD

**Issue by JosenJiang** [m0in92/EV_sim#4]
Hello, thanks to share this great work!
When I run `python setup.py sdist`, it raises error: package directory 'EV_sim/examples' does not exist.
What should I do to fix it?

**Comment by m0in92** [comment]
I appreciate your comment!

I have updated this repository to include a new setup.py. 

Please clone the updated repository and try again. Please let me know of any issues during the installation. I will be working tomorrow for a better installation method and updated README.md

**Comment by KaVo194** [comment]
Hello, 
When Installing via 'python setup.py sdist' I get a  _ModuleNotFoundError: No module named 'customtkinter'_
How can I fix that?

> `Traceback (most recent call last):
  File "/Users/kaivoigt/EV_sim-main/setup.py", line 2, in <module>
    from EV_sim.version import __version__
  File "/Users/kaivoigt/EV_sim-main/EV_sim/__init__.py", line 15, in <module>
    from .tkinter_gui.main import VehicleDynamicsApp
  File "/Users/kaivoigt/EV_sim-main/EV_sim/tkinter_gui/main.py", line 9, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'
`
