### ISSUE TITLE
cant run with usage

### ISSUE THREAD

**Issue by FireJohnny** [m0in92/EV_sim#5]
when i run with `python -m EV_sim` i got error
```AttributeError: 'DriveCycle' object has no attribute 't'```
python：3.11.4
system: windows 10
ide: pycharm

**Comment by m0in92** [comment]
Hi, thank you for letting me know of the error. It seems to be working at my end. If it's not a problem, can you copy all of the error messages displayed when you execute that command?

**Comment by FireJohnny** [comment]
> Hi, thank you for letting me know of the error. It seems to be working at my end. If it's not a problem, can you copy all of the error messages displayed when you execute that command?
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AppData\Local\miniconda3\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "C:\Users\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 210, in lstbox_callback
    self.parent.parent.DisplayFrameInstance.create_widget(self.main_heading_text + '-' + category +
  File "C:\Users\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 384, in create_widget
    SubDisplayPlots(self, plot_info_dict=self.plot_info_dict[category],user_selection=user_selection)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 329, in plot_info_dict
    'Desired Acceleration': [sol_obj.t, sol_obj.des_acc, 'Time [min]', r'Desired Acceleration [m/$s^2$]'],
                             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 't'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AppData\Local\miniconda3\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "C:\Users\Desktop\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 210, in lstbox_callback
    self.parent.parent.DisplayFrameInstance.create_widget(self.main_heading_text + '-' + category +
  File "C:\Users\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 384, in create_widget
    SubDisplayPlots(self, plot_info_dict=self.plot_info_dict[category],user_selection=user_selection)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\batteries_smiu\EV_sim\EV_sim-main\EV_sim\tkinter_gui\main.py", line 329, in plot_info_dict
    'Desired Acceleration': [sol_obj.t, sol_obj.des_acc, 'Time [min]', r'Desired Acceleration [m/$s^2$]'],
                             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 't'
```

here is the error stack info

**Comment by m0in92** [comment]
In the GUI, if you click on the External Conditions > input the values of the air pressure, road grade, and road force > Press Simulate (on the top bar). 

Then you will be able to view the simulation results by clicking on any of the results in the results options.

An error is shown in case of missing inputs.
